bricks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', include('website.urls')),
    path('voting/', include('voting.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# to import static in deployment

voting/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from allauth.account.views import LoginView, SignupView

app_name = 'voting'  # here for namespacing of urls.

urlpatterns = [
    #     path("", views.votingHomepage, name="votingHomepage"),

    path("", views.login_request, name="login"),
    # no need for a 'homepage, only login and myvotes are needed, the navbar will change from logo to dashboard link if user is staff
    # TODO: remove logout view, only use as function?
    # see: https://www.squarefree.com/securitytips/web-developers.html#CSRF:~:text=Log%20the%20victim%20out%20of%20your%20site.%20(On%20some%20sites%2C%20%22Log%20out%22%20is%20a%20link%20rather%20than%20a%20button!)
    #     path("register/", views.register, name="register"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path("myvotes/", views.myVotes, name="myvotes"),

    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/addcreation/", views.addCreation, name="addcreation"),
    path('edit/<int:pk>/', views.CreationUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.CreationDeleteView.as_view(), name='delete'),
    path("dashboard/stats/", views.stats, name="stats"),
    path("dashboard/allcreations/", views.allCreations, name="allcreations"),
    #     path(r'/accountslogin/', LoginView.as_view(), name="custom_login"),
    #     path(r'signup/', SignupView.as_view(), name="custom_singup"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

voting/models.py
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from bricks import settings
# Create your models here.


class Creation(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    creator = models.CharField(max_length=100)
    image = models.ImageField(
        upload_to='creations/')
    number = models.IntegerField(unique=True)

    def __str__(self):
        return self.name


class VotingList(models.Model):
    CHOICES = [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]
    # add one-to-one relationship with user
    # user = models.OneToOneField(
    # User, on_delete=models.CASCADE, primary_key=True)

    # add many-to-one relationship with user
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # add many-to-many relationship with Creation
    creation = models.ManyToManyField(Creation)

    CATEGORIES = ["creativiteit", "details", "indrukwekkend"]
    category = models.CharField(max_length=20)

    vote = models.IntegerField(blank=True, null=True)

voting/forms.py
from ast import Attribute
from django import forms
from .models import Creation, VotingList
from django.forms import ModelForm
from django.db import models
from django.forms import ModelForm


class CreationForm(ModelForm):
    class Meta:
        model = Creation
        fields = ['number', 'name', 'description', 'creator', 'image']
        widgets = {
            'number': forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 50%; margin: 0 auto; margin-bottom: 10px; font-size: 3rem; font-weight: bold; color: #000; background-color: #fff;'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'style': 'width: 50%; margin: 0 auto; margin-bottom: 10px; font-size: 3rem; font-weight: bold; color: #000; background-color: #fff;'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'style': 'width: 50%; margin: 0 auto; margin-bottom: 10px; font-size: 3rem; font-weight: bold; color: #000; background-color: #fff;'}),
            'creator': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'style': 'width: 50%; margin: 0 auto; margin-bottom: 10px; font-size: 3rem; font-weight: bold; color: #000; background-color: #fff;'}),
            'image': forms.FileInput(attrs={'accept': 'image/*', 'capture': 'camera'})



            # 'number': forms.NumberInput(widget=forms.IntegerField(attrs={'class': 'form-control'})),
            # 'name': forms.TextInput(widget=forms.TextInput(attrs={'class': 'form-control'})),
            # 'description': forms.TextInput(widget=forms.TextInput(attrs={'class': 'form-control'})),
            # 'creator': forms.TextInput(widget=forms.TextInput(attrs={'class': 'form-control'})),
            # 'image': forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'})),
        }
# class CreationForm(forms.Form):
#     name = forms.CharField(max_length=200)
#     description = forms.CharField(max_length=200)
#     creator = forms.CharField(max_length=200)
#     image = forms.ImageField(required=False)


class VotingForm(forms.Form):

    # choices for the radiobuttons (stars/ legobricks) in the voting form, (value, name)
    # CHOICES = [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]

    # user enters vote
    vote = forms.ChoiceField(
        choices=VotingList.CHOICES, widget=forms.RadioSelect, required=False)

    # user enters vote (submits on change)
    # vote = forms.ChoiceField(choices=CHOICES,
    #                          widget=forms.RadioSelect(attrs={'onchange': 'actionform.submit();'}), required=FALSE)

    # place to keep track of the creation
    creationId = forms.IntegerField(widget=forms.HiddenInput)
    category = forms.CharField(max_length=20, widget=forms.HiddenInput)
    # creationId = forms.IntegerField()

voting/views.py
import json
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.db.models import Avg, Min, Max, Count, Sum, FloatField, F
from django.views.generic import UpdateView, DeleteView
from django.conf import settings
from django.db.models.functions import Coalesce
from voting.forms import *
from voting.models import *

# Create your views here.

# tests


def userIsStaff(user):
    return user.is_staff


def is_helper(user):
    print(user, "is_helper")
    return user.groups.filter(name='helper').exists()


def votingHomepage(request):
    return render(request=request,
                  template_name='voting/votingHomepage.html',
                  context={}
                  )


# def register(request):
#     if request.method == "POST":
#         print("POST")
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             username = form.cleaned_data.get('username')
#             messages.success(request, f"New account created: {username}")
#             login(request, user)
#             # TODO: login and route to myvotes
#             # return redirect("voting:votingHomepage")
#             return redirect("voting:myvotes")

#         else:
#             for msg in form.error_messages:
#                 messages.error(request, f"{msg}: {form.error_messages[msg]}")

#             return render(request=request,
#                           template_name="voting/register.html",
#                           context={"form": form})

    # elif request.method == "GET":
    form = UserCreationForm
    return render(request=request,
                  template_name="voting/register.html",
                  context={"form": form}
                  )


def login_request(request):
    if request.user.is_authenticated:
        messages.info(request, "You are logged in.")
        return redirect('voting:myvotes')

    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect('voting:myvotes')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request,
                  template_name="voting/login.html",
                  context={"form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")  # TODO messages
    return redirect("website:homepage")


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

# request.headers.get('x-requested-with') == 'XMLHttpRequest'


@login_required  # TODO add this
def myVotes(request):
    # handle a post through ajax
    if request.method == "POST" and request.headers.get('x-requested-with') == 'XMLHttpRequest':
        submission = json.loads(request.body.decode('utf-8'))
        # print(f"submission: {submission}")
        # print(f"submission['vote']: {submission['vote']}")
        # print(f"submission['creationId']: {submission['creationId']}")
        # print(f"submission['category']: {submission['category']}")

        user = request.user
        creationId = submission['creationId']
        category = submission['category']
        vote = submission['vote']
        # print(
        #     f"creationID: {creationId} category: {category}, voteValue: {vote}, user: {user}")

        # if user does not have a VotingList, create one and add the vote
        if not VotingList.objects.filter(user=user, creation=Creation.objects.get(id=creationId), category=category).exists():
            print("Does not exist")
            # if not VotingList.objects.filter(user=user, creation=creation).exists():
            votedCreation = Creation.objects.get(id=creationId)

            newVotingList = VotingList(user=user,
                                       vote=vote,
                                       category=category,
                                       )
            newVotingList.save()
            newVotingList.creation.set([votedCreation])

        # if user does have a VotingList, add the vote to the list
        elif VotingList.objects.filter(user=user, creation=Creation.objects.get(id=creationId), category=category).exists():
            # elif VotingList.objects.filter(user=user, creation=creation).exists():
            updateVotingList = VotingList.objects.get(
                user=user, creation=Creation.objects.get(id=creationId), category=category)
            updateVotingList.vote = vote
            updateVotingList.save()
            # print(f'{"updated":_^15}')

        # print("submission: ", submission)
        return JsonResponse(submission)

    elif request.method == "GET":
        # make a dictionary of all creations and a form for them,
        # then add an attribute to fill in the current vote, if there is one, as an initial value

        # formList contains all forms and needed values
        formList = []
        for creation in Creation.objects.all().order_by("number"):
            # formListItems contains each individual creation, form and vote if there is one
            # {'creation': creation, 'forms': {creativity: form(), uniqueness: form(), impressiveness: form()}, 'vote': currentvote}
            formListItems = {}
            # add the creation to the formListItems dictionary
            formListItems['creation'] = creation

            categoryForms = {}
            for category in VotingList.CATEGORIES:
                if VotingList.objects.filter(
                        user=request.user,
                        creation=Creation.objects.get(id=creation.id), category=category).exists():
                    # get the vote
                    currentVote = VotingList.objects.filter(
                        user=request.user, creation=Creation.objects.get(id=creation.id), category=category).get().vote
                else:
                    currentVote = None

                # add the current vote for that category to the formListItems
                categoryForm = {"form": VotingForm(), "vote": currentVote}
                categoryForms[category] = categoryForm
            formListItems['categoryForms'] = categoryForms
            formList.append(formListItems)

        return render(request=request,
                      template_name="voting/myvotes.html",
                      context={
                          "formList": formList,
                          # "creations": Creation.objects.all(),
                          "votingLists": VotingList.objects.filter(user_id=request.user.id)
                      })

        #   https://stackoverflow.com/questions/11165267/django-redirect-with-anchor-parameters

        # https://stackoverflow.com/questions/58645505/how-to-render-a-field-request-without-refreshing-the-page/58645877#58645877


#############
# DASHBOARD #
#############

@user_passes_test(is_helper)
# @user_passes_test((lambda u: u.is_staff))
def dashboard(request):

    return render(request=request,
                  template_name="voting/dashboard.html",
                  context={"creations": Creation.objects.all()
                           })


@ user_passes_test(is_helper)
def stats(request):
    # build a dictionary of the highest voted creations
    # The dictionary will be cut off using slicing. It could be done easier by using negative indexing [-setting.STAT_AMOUNT:], but Django does not support this.

    def subSetOfQuery(querySet, lowToHigh=False):
        splice = min(settings.STAT_AMOUNT, len(querySet))
        return querySet[:splice]

    # dictionary of creation its avg vote regardless of category
    # Coalesce is used to return 0 if there is no vote, it returns the first non-null value (so either the Avg() or 0 in  this case)
    # highest
    highestAvgPerCreation = Creation.objects.annotate(
        avg=Coalesce(Avg("votinglist__vote"), 0, output_field=FloatField())).order_by("-avg")
    highestAvgPerCreation = subSetOfQuery(highestAvgPerCreation)

    # lowest
    lowestAvgPerCreation = Creation.objects.annotate(
        avg=Coalesce(Avg("votinglist__vote"), 0, output_field=FloatField())).order_by("avg")
    lowestAvgPerCreation = subSetOfQuery(lowestAvgPerCreation)

    # dictionary of creation id and its avg vote per category
    # Creativity
    # highest

    highestCrea = Creation.objects.filter(votinglist__category__startswith="crea").annotate(
        avg=Avg("votinglist__vote")).order_by("-avg")
    highestCrea = subSetOfQuery(highestCrea)

    # lowest
    lowestCrea = Creation.objects.filter(votinglist__category__startswith="crea").annotate(
        avg=Avg("votinglist__vote")).order_by("avg")
    lowestCrea = subSetOfQuery(lowestCrea)

    # Impressiveness
    # highest
    highestImpr = Creation.objects.filter(votinglist__category__startswith="indr").annotate(
        avg=Avg("votinglist__vote")).order_by("-avg")
    highestImpr = subSetOfQuery(highestImpr)

    # lowest
    lowestImpr = Creation.objects.filter(votinglist__category__startswith="indr").annotate(
        avg=Avg("votinglist__vote")).order_by("avg")
    lowestImpr = subSetOfQuery(lowestImpr)

    # Details
    # highest

voting/templates/voting/includes/footer.html
{% comment %} <div class="text-center bg-bamBlue text-slate-300 font-semibold py-2 text-5xl w-screen flex"> {% endcomment %}
{% load static %}
<link rel="stylesheet" href="{% static 'voting/css/output.css' %}">
<div class="text-center bg-bamBlue text-slate-300 font-semibold py-2 text-5xl mt-3">
    <div class="px-12 mb-2 bg-bamBlue flex content-between justify-between text-bamDarkText font-semibold">
        <div>
            <a href="https://www.thomasmore.be/">
                <img src="{% static 'voting/logoTM.png' %}" alt="logo Thomas More" class="object-contain w-auto h-14">
            </a>
        </div>
        <div class="w-2/5">

        </div>
        <div class="text-xl flex-1">
            met 🖤 gemaakt door <a href="https://github.com/FrederikGielis " class="underline">Frederik</a> voor <a href="https://bricks-and-more.be/" class="underline">BaM</a> als project voor 
            <a href="https://digitalinnovation.be/" class="underline">Digital Innovation</a>
        </div>
    </div>
</div>

voting/templates/voting/includes/messages.html
{% comment %} {% if messages %}
{% for message in messages %}
    {% if message.tags == 'success'%}
        <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
    {% elif message.tags == 'info'%}
        <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
    {% elif message.tags == 'warning'%}
        <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
    {% elif message.tags == 'error'%}
        <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
    {% endif %}
{% endfor %}
{% endif %} {% endcomment %}


<div class="flex flex-col fixed bottom-1 inset-x-0 mx-auto px-4 py-3 z-50 w-3/4 gap-y-2">
    {% if messages %}
        <div id="messages" class="messages bg-blue-100 border border-blue-500 text-blue-700 rounded-md text-center">
        <ul>
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
        </div>
    {% endif %}


    {% if errors %}
    <div id="errors" class="messages bg-red-100 border border-red-500 text-red-700 rounded-md text-center">
        {% for error in errors %}
        <li>{{ error }}</li>
    {% endfor %}
    </ul>
    </div>
    {% endif %}

voting/templates/voting/includes/nav.html
{% load voting_extras %}
{% load static %}
<link rel="stylesheet" href="{% static 'voting/css/output.css' %}">
<div class="text-center bg-bamBlue text-slate-300 font-semibold py-2 text-5xl">
    <nav class="px-12 mb-2 bg-bamBlue flex content-between justify-between text-slate-500 font-semibold">
        {% comment %} if staff show dashboard link, else show logo {% endcomment %}
    
    {% if request.user|has_group:"helper" or request.user.is_staff %}
        <div  class="my-auto">
            <a href="{% url 'voting:dashboard' %}">Dashboard</a>
        </div>
        {% else %}
        <div class="my-auto">
        <img src="{% static 'voting/logo.png' %}" alt="logo" class="object-contain w-auto h-14">
    </div>
    {% comment %} <div class="my-auto bg-purple-600 h-3 container">
        <img src="{% static 'voting/logo.png' %}" alt="logo" class="object-contain">
    </div> {% endcomment %}
    {% endif %}
    {% if user.is_authenticated %}
    <div  class="my-auto">
        <a href="{% url 'voting:logout' %}">Logout</a>
    </div>
    {% endif %}
</nav>
</div>

voting/templates/voting/includes/navwithsearch.html
{% load static %}
<link rel="stylesheet" href="{% static 'voting/css/output.css' %}">

<div class="sticky top-0 z-50 text-5xl">
    {% comment %} NUMBER SEARCH FORM {% endcomment %}
    <div class="text-center bg-bamBlue text-slate-300 font-semibold py-2 sticky top-0 z-50">
        <div class="">
            <form id="search" class="flex place-content-center my-auto">
                <label class="flex-auto">Ga naar nr:</label>
                <input class="flex-auto w-1" id="number" name="number">
                <div class="flex-auto">
                    <div class="border-solid border-2 border-slate-300 inline-block p-2 bg-slate-700">
                        <input type="submit" value="Zoek!">
                    </div>
                </div>
            </form>
    </div>
</div>

voting/templates/voting/includes/status.html
{% comment %} <div>
    <p>
        {% if user.is_authenticated %}
        You are logged in as <strong>{{ user.username }}</strong>.
        {% else %}
        You are not logged in.
        {% endif %}
    </p>
</div> {% endcomment %}