bricks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', include('website.urls')),
    path('voting/', include('voting.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# to import static in deployment

voting/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from allauth.account.views import LoginView, SignupView

app_name = 'voting'  # here for namespacing of urls.

urlpatterns = [
    #     path("", views.votingHomepage, name="votingHomepage"),

    path("", views.login_request, name="login"),
    # no need for a 'homepage, only login and myvotes are needed, the navbar will change from logo to dashboard link if user is staff
    # TODO: remove logout view, only use as function?
    # see: https://www.squarefree.com/securitytips/web-developers.html#CSRF:~:text=Log%20the%20victim%20out%20of%20your%20site.%20(On%20some%20sites%2C%20%22Log%20out%22%20is%20a%20link%20rather%20than%20a%20button!)
    #     path("register/", views.register, name="register"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path("myvotes/", views.myVotes, name="myvotes"),

    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/addcreation/", views.addCreation, name="addcreation"),
    path('edit/<int:pk>/', views.CreationUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.CreationDeleteView.as_view(), name='delete'),
    path("dashboard/stats/", views.stats, name="stats"),
    path("dashboard/allcreations/", views.allCreations, name="allcreations"),
    #     path(r'/accountslogin/', LoginView.as_view(), name="custom_login"),
    #     path(r'signup/', SignupView.as_view(), name="custom_singup"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

voting/models.py
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from bricks import settings
# Create your models here.


class Creation(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    creator = models.CharField(max_length=100)
    image = models.ImageField(
        upload_to='creations/')
    number = models.IntegerField(unique=True)

    def __str__(self):
        return self.name


class VotingList(models.Model):
    CHOICES = [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]
    # add one-to-one relationship with user
    # user = models.OneToOneField(
    # User, on_delete=models.CASCADE, primary_key=True)

    # add many-to-one relationship with user
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # add many-to-many relationship with Creation
    creation = models.ManyToManyField(Creation)

    CATEGORIES = ["creativiteit", "details", "indrukwekkend"]
    category = models.CharField(max_length=20)

    vote = models.IntegerField(blank=True, null=True)

voting/forms.py
from ast import Attribute
from django import forms
from .models import Creation, VotingList
from django.forms import ModelForm
from django.db import models
from django.forms import ModelForm


class CreationForm(ModelForm):
    class Meta:
        model = Creation
        fields = ['number', 'name', 'description', 'creator', 'image']
        widgets = {
            'number': forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 50%; margin: 0 auto; margin-bottom: 10px; font-size: 3rem; font-weight: bold; color: #000; background-color: #fff;'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'style': 'width: 50%; margin: 0 auto; margin-bottom: 10px; font-size: 3rem; font-weight: bold; color: #000; background-color: #fff;'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'style': 'width: 50%; margin: 0 auto; margin-bottom: 10px; font-size: 3rem; font-weight: bold; color: #000; background-color: #fff;'}),
            'creator': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'style': 'width: 50%; margin: 0 auto; margin-bottom: 10px; font-size: 3rem; font-weight: bold; color: #000; background-color: #fff;'}),
            'image': forms.FileInput(attrs={'accept': 'image/*', 'capture': 'camera'})



            # 'number': forms.NumberInput(widget=forms.IntegerField(attrs={'class': 'form-control'})),
            # 'name': forms.TextInput(widget=forms.TextInput(attrs={'class': 'form-control'})),
            # 'description': forms.TextInput(widget=forms.TextInput(attrs={'class': 'form-control'})),
            # 'creator': forms.TextInput(widget=forms.TextInput(attrs={'class': 'form-control'})),
            # 'image': forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'})),
        }
# class CreationForm(forms.Form):
#     name = forms.CharField(max_length=200)
#     description = forms.CharField(max_length=200)
#     creator = forms.CharField(max_length=200)
#     image = forms.ImageField(required=False)


class VotingForm(forms.Form):

    # choices for the radiobuttons (stars/ legobricks) in the voting form, (value, name)
    # CHOICES = [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]

    # user enters vote
    vote = forms.ChoiceField(
        choices=VotingList.CHOICES, widget=forms.RadioSelect, required=False)

    # user enters vote (submits on change)
    # vote = forms.ChoiceField(choices=CHOICES,
    #                          widget=forms.RadioSelect(attrs={'onchange': 'actionform.submit();'}), required=FALSE)

    # place to keep track of the creation
    creationId = forms.IntegerField(widget=forms.HiddenInput)
    category = forms.CharField(max_length=20, widget=forms.HiddenInput)
    # creationId = forms.IntegerField()

voting/views.py
import json
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.db.models import Avg, Min, Max, Count, Sum, FloatField, F
from django.views.generic import UpdateView, DeleteView
from django.conf import settings
from django.db.models.functions import Coalesce
from voting.forms import *
from voting.models import *

# Create your views here.

# tests


def userIsStaff(user):
    return user.is_staff


def is_helper(user):
    print(user, "is_helper")
    return user.groups.filter(name='helper').exists()


def votingHomepage(request):
    return render(request=request,
                  template_name='voting/votingHomepage.html',
                  context={}
                  )


# def register(request):
#     if request.method == "POST":
#         print("POST")
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             username = form.cleaned_data.get('username')
#             messages.success(request, f"New account created: {username}")
#             login(request, user)
#             # TODO: login and route to myvotes
#             # return redirect("voting:votingHomepage")
#             return redirect("voting:myvotes")

#         else:
#             for msg in form.error_messages:
#                 messages.error(request, f"{msg}: {form.error_messages[msg]}")

#             return render(request=request,
#                           template_name="voting/register.html",
#                           context={"form": form})

    # elif request.method == "GET":
    form = UserCreationForm
    return render(request=request,
                  template_name="voting/register.html",
                  context={"form": form}
                  )


def login_request(request):
    if request.user.is_authenticated:
        messages.info(request, "You are logged in.")
        return redirect('voting:myvotes')

    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect('voting:myvotes')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request,
                  template_name="voting/login.html",
                  context={"form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")  # TODO messages
    return redirect("website:homepage")


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

# request.headers.get('x-requested-with') == 'XMLHttpRequest'


@login_required  # TODO add this
def myVotes(request):
    # handle a post through ajax
    if request.method == "POST" and request.headers.get('x-requested-with') == 'XMLHttpRequest':
        submission = json.loads(request.body.decode('utf-8'))
        # print(f"submission: {submission}")
        # print(f"submission['vote']: {submission['vote']}")
        # print(f"submission['creationId']: {submission['creationId']}")
        # print(f"submission['category']: {submission['category']}")

        user = request.user
        creationId = submission['creationId']
        category = submission['category']
        vote = submission['vote']
        # print(
        #     f"creationID: {creationId} category: {category}, voteValue: {vote}, user: {user}")

        # if user does not have a VotingList, create one and add the vote
        if not VotingList.objects.filter(user=user, creation=Creation.objects.get(id=creationId), category=category).exists():
            print("Does not exist")
            # if not VotingList.objects.filter(user=user, creation=creation).exists():
            votedCreation = Creation.objects.get(id=creationId)

            newVotingList = VotingList(user=user,
                                       vote=vote,
                                       category=category,
                                       )
            newVotingList.save()
            newVotingList.creation.set([votedCreation])

        # if user does have a VotingList, add the vote to the list
        elif VotingList.objects.filter(user=user, creation=Creation.objects.get(id=creationId), category=category).exists():
            # elif VotingList.objects.filter(user=user, creation=creation).exists():
            updateVotingList = VotingList.objects.get(
                user=user, creation=Creation.objects.get(id=creationId), category=category)
            updateVotingList.vote = vote
            updateVotingList.save()
            # print(f'{"updated":_^15}')

        # print("submission: ", submission)
        return JsonResponse(submission)

    elif request.method == "GET":
        # make a dictionary of all creations and a form for them,
        # then add an attribute to fill in the current vote, if there is one, as an initial value

        # formList contains all forms and needed values
        formList = []
        for creation in Creation.objects.all().order_by("number"):
            # formListItems contains each individual creation, form and vote if there is one
            # {'creation': creation, 'forms': {creativity: form(), uniqueness: form(), impressiveness: form()}, 'vote': currentvote}
            formListItems = {}
            # add the creation to the formListItems dictionary
            formListItems['creation'] = creation

            categoryForms = {}
            for category in VotingList.CATEGORIES:
                if VotingList.objects.filter(
                        user=request.user,
                        creation=Creation.objects.get(id=creation.id), category=category).exists():
                    # get the vote
                    currentVote = VotingList.objects.filter(
                        user=request.user, creation=Creation.objects.get(id=creation.id), category=category).get().vote
                else:
                    currentVote = None

                # add the current vote for that category to the formListItems
                categoryForm = {"form": VotingForm(), "vote": currentVote}
                categoryForms[category] = categoryForm
            formListItems['categoryForms'] = categoryForms
            formList.append(formListItems)

        return render(request=request,
                      template_name="voting/myvotes.html",
                      context={
                          "formList": formList,
                          # "creations": Creation.objects.all(),
                          "votingLists": VotingList.objects.filter(user_id=request.user.id)
                      })

        #   https://stackoverflow.com/questions/11165267/django-redirect-with-anchor-parameters

        # https://stackoverflow.com/questions/58645505/how-to-render-a-field-request-without-refreshing-the-page/58645877#58645877


#############
# DASHBOARD #
#############

@user_passes_test(is_helper)
# @user_passes_test((lambda u: u.is_staff))
def dashboard(request):

    return render(request=request,
                  template_name="voting/dashboard.html",
                  context={"creations": Creation.objects.all()
                           })


@ user_passes_test(is_helper)
def stats(request):
    # build a dictionary of the highest voted creations
    # The dictionary will be cut off using slicing. It could be done easier by using negative indexing [-setting.STAT_AMOUNT:], but Django does not support this.

    def subSetOfQuery(querySet, lowToHigh=False):
        splice = min(settings.STAT_AMOUNT, len(querySet))
        return querySet[:splice]

    # dictionary of creation its avg vote regardless of category
    # Coalesce is used to return 0 if there is no vote, it returns the first non-null value (so either the Avg() or 0 in  this case)
    # highest
    highestAvgPerCreation = Creation.objects.annotate(
        avg=Coalesce(Avg("votinglist__vote"), 0, output_field=FloatField())).order_by("-avg")
    highestAvgPerCreation = subSetOfQuery(highestAvgPerCreation)

    # lowest
    lowestAvgPerCreation = Creation.objects.annotate(
        avg=Coalesce(Avg("votinglist__vote"), 0, output_field=FloatField())).order_by("avg")
    lowestAvgPerCreation = subSetOfQuery(lowestAvgPerCreation)

    # dictionary of creation id and its avg vote per category
    # Creativity
    # highest

    highestCrea = Creation.objects.filter(votinglist__category__startswith="crea").annotate(
        avg=Avg("votinglist__vote")).order_by("-avg")
    highestCrea = subSetOfQuery(highestCrea)

    # lowest
    lowestCrea = Creation.objects.filter(votinglist__category__startswith="crea").annotate(
        avg=Avg("votinglist__vote")).order_by("avg")
    lowestCrea = subSetOfQuery(lowestCrea)

    # Impressiveness
    # highest
    highestImpr = Creation.objects.filter(votinglist__category__startswith="indr").annotate(
        avg=Avg("votinglist__vote")).order_by("-avg")
    highestImpr = subSetOfQuery(highestImpr)

    # lowest
    lowestImpr = Creation.objects.filter(votinglist__category__startswith="indr").annotate(
        avg=Avg("votinglist__vote")).order_by("avg")
    lowestImpr = subSetOfQuery(lowestImpr)

    # Details
    # highest

voting/templates/voting/addcreation.html
{% extends 'voting/header.html' %}

{% block content %}
{% include "voting/includes/status.html" %}

{% comment %} part of this form is styled using attributes, see forms.py {% endcomment %}

<div class="mx-9">
    <div class="flex justify-between">
        <div>
            <h2 class="text-6xl text-bamDarkText font-bold my-8">Voeg nieuw bouwwerk toe</h2>
        </div>
        <div class="items-center flex">
            <a href="{% url 'voting:allcreations' %}" class="text-white bg-blue-700 font-medium rounded-lg text-5xl px-5 py-2.5 mr-2 my-8">Terug</a>
        </div>
    </div>



<div class="mx-9">
    
    <form method="POST" method="post" accept-charset="utf-8" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.non_field_errors }}

        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field.errors }}
            {{ hidden_field }}
        {% endfor %}
        <div>
            {% for field in form.visible_fields %}
                <div class="block mb-2 text-7xl font-medium">
                    {{ field.label_tag }}
                </div>

                <div>
                    {{ field.errors }}
                </div>

                <div>
                    {{ field }}
                </div>

                <div>
                    {{ field.help_text }}
                </div>
                
            {% endfor %}
        </div>
        <button type="submit" class="text-white bg-blue-700 font-medium rounded-lg text-5xl px-5 py-2.5 mr-2 my-8">Toevoegen</button>
    </form>
</div>    
{% endblock %}

voting/templates/voting/allcreations.html
{% extends 'voting/header.html' %}

{% block content %}
{% include "voting/includes/status.html" %}


<div class="flex flex-row place-content-between mt-5">
    <div class="text-bamDarkText text-8xl font-bold px-5 self-center">
        <h2>Alle bouwwerken</h2>
    </div>
    <div class="flex my-auto">
        <a href="{% url 'voting:addcreation' %}" class="text-white bg-blue-700 font-medium rounded-lg text-5xl px-5 py-2.5 mr-2 mb-2">Nieuw</a>
    </div>
</div>
    <div class="grid-flow-col grid-cols-2 mx-3 text-5xl">
        {% for creation in creations %}
        <div class="border border-solid border-black rounded-2xl my-2 p-2">
            <div class="flex justify-between">

                <h3 class=" text-bamDarkText font-bold my-5">
                    {{creation.number}}. {{ creation.name }} 
                </h3> 
                
                <a href="{% url 'voting:edit' creation.id %} " class="text-white bg-blue-700 font-medium rounded-lg text-5xl px-5 py-2.5 m-5">Wijzig</a>
            </div>

            <div class="grid grid-flow-col grid-cols-2">
                <div class="col-span-1">
                    <img src="{{ creation.image.url }}" alt="..."  width="250" height="250">
                </div>
                <div class="col-span-1">
                        <div class="my-2 text-bamText">Beschrijving:</div>
                        <div class="my-2 text-bamDarkText font-bold">{{ creation.description }}</div>
                        <div class="my-2 text-bamText">door:</div>
                        <div class="my-2 text-bamDarkText font-bold">{{ creation.creator }}</div>
                </div>
                <div class="flex self-end p-2">
                <a href="{% url 'voting:delete' creation.id %}" class="text-white bg-red-700 font-medium rounded-lg text-5xl px-5 py-2.5 m-5">Verwijder</a>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

voting/templates/voting/creation_confirm_delete.html
{% extends 'voting/header.html' %}

{% block content %}
{% include "voting/includes/status.html" %}


<div class="h-screen grid place-items-center">
    <div class="grid grid-flow-col columns-1 grid-rows-3 gap-y-12  place-items-center w-1/2">
        <div class="text-bamDarkText text-5xl font-bold px-5 flex self-center text-center">Ben je zeker dat je "{{ object }}" wil verwijderen?</div>
        <form method="post">{% csrf_token %}
            {{ form }}
            <div class="flex self-center justify-around">
                <img src="{{ object.image.url }}" alt="..."  width="250"        height="250">
            </div>
            <div class="flex self-center py-12 justify-between">
                <div class="mx-auto">
                    <input type="submit" value="Confirm" class="text-white bg-red-700 font-medium rounded-lg text-5xl px-5 py-2.5 mr-2 my-8">
                </div>
                <a href="{% url 'voting:allcreations' %}" class="text-white bg-blue-700 font-medium rounded-lg text-5xl px-5 py-2.5 mr-2 my-8">Terug</a>
            </div>
        </form>
    </div>
</div>

{% comment %} <div class="flex self-center">
    <div >
        
    </div>

</div> {% endcomment %}

{% endblock %}

voting/templates/voting/dashboard.html
{% extends 'voting/header.html' %}
{% block content %}

<br>


<div class="h-screen grid place-items-center">
    <div class="grid grid-flow-col columns-1 grid-rows-3 gap-y-40 place-items-center">
        <div class="col-span-1">
            <a href="{% url 'voting:stats' %}" class="text-slate-100 bg-blue-700 rounded-lg text-6xl px-5 py-2.5 ">Statistieken</a>
        </div>
        <div class="col-span-1">
            <a href="{% url 'voting:allcreations' %}" class="text-slate-100 bg-blue-700 rounded-lg text-6xl px-5 py-2.5 ">Overzicht creaties</a>
        </div>
        <div class="col-span-1">        
            <a href="{% url 'voting:myvotes' %}" class="text-slate-100 bg-blue-700 rounded-lg text-6xl px-5 py-2.5 ">Terug naar stemmen</a>
        </div>
    </div>
</div>


{% endblock %}

voting/templates/voting/edit.html
{% extends 'voting/header.html' %}

{% block content %}
{% include "voting/includes/status.html" %}

{% comment %} part of this form is styled using attributes, see forms.py {% endcomment %}
<div class="mx-9">
    <div class="flex justify-between">
        <div>
            <h2 class="text-6xl text-bamDarkText font-bold my-8">Wijzig "{{creation.name}}"</h2>
        </div>
        <div class="items-center flex">
            <a href="{% url 'voting:allcreations' %}" class="text-white bg-blue-700 font-medium rounded-lg text-5xl px-5 py-2.5 mr-2 my-8">Terug</a>
        </div>
    </div>
    <form method="POST" method="post" accept-charset="utf-8" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.non_field_errors }}

        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field.errors }}
            {{ hidden_field }}
        {% endfor %}
        <div>
            {% for field in form.visible_fields %}
                <div class="block mb-2 text-7xl font-medium">
                    {{ field.label_tag }}
                </div>
                <div>
                    {{ field.errors }}
                </div>
                <div>
                    {{ field }}
                </div>
                <div>
                    {{ field.help_text }}
                </div>
            {% endfor %}
        </div>
        <button type="submit" class="text-white bg-blue-700 font-medium rounded-lg text-5xl px-5 py-2.5 mr-2 my-8">Wijzigen</button>
    </form>
</div>    
{% endblock %}

voting/templates/voting/header.html
<head>
  {% load static %}
  <link rel="stylesheet" href="{% static 'voting/css/output.css' %}">
  <script src="{% static 'js/messages.js' %}" defer></script>
</head>

<body class="bg-slate-200 flex flex-col  h-full">
  {% comment %} ex nav {% endcomment %}
  {% include "voting/includes/nav.html" %}
  <div class="flex-grow">
    {% block content %}
    {% endblock %}
  </div>
  <div class="flex-grow-0">
    {% include "voting/includes/footer.html" %}
  </div>
  {% include "voting/includes/messages.html" %}
</body>

voting/templates/voting/login.html
{% extends 'voting/header.html' %}

{% block content %}
{% load socialaccount %}
{% include "socialaccount/snippets/login_extra.html" %}

{% comment %} <div>
    <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
        <button style="background-color:#F4EB16; color:blue" type="submit">Login</button>
    </form>
    Don't have an account? <a href="{% url 'voting:register' %}" target=""><strong>register here</strong></a>!
</div> {% endcomment %}


<div class="h-screen grid place-items-center ">

    <div class="flex flex-col items-center pb-16">

        <div class="text-5xl">
        Log je in om te beginnen met stemmen!
        </div>

        <div class="py-16">
            {% comment %} GOOGLE {% endcomment %}
            <form action="{% provider_login_url 'google' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="text-white bg-[#d0463b] hover:bg-[#ff6148]/90 font-medium rounded-lg text-5xl px-5 py-2.5 text-center inline-flex items-center mr-2 mb-2">
                    <svg class="mr-2 -ml-1 w-24 h-18 p-4" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="google" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 488 512"><path fill="currentColor" d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z"></path></svg>
                    Sign in with Google
                </button>
            </form>
        </div>


        <div class="max-h-10 w-full flex justify-around">
            {% comment %} FACEBOOK {% endcomment %}
            <form action="{% provider_login_url 'facebook' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="text-white bg-[#3b5998] hover:bg-[#7790db]/90 font-medium rounded-lg text-5xl px-5 py-2.5 text-center inline-flex items-center mr-2 mb-2">
                    <svg class="mr-2 -ml-1 w-24 h-18 p-4" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="google" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 488 512"><path fill="currentColor" d="M279.1 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.4 0 225.4 0c-73.22 0-121.1 44.38-121.1 124.7v70.62H22.89V288h81.39v224h100.2V288z"></path></svg>
                    Sign in with Facebook
                </button>
            </form>
        </div>
    </div>
</div>
    
    
    

    {% comment %} TWITTER {% endcomment %}
    {% comment %} <div>
        <form action="{% provider_login_url 'twitter' %}" method="post">
            {% csrf_token %}
            <button type="submit">Twitter</button>
        </form>
    </div> {% endcomment %}
    {% comment %} FACEBOOK {% endcomment %}
    
    
    
    {% comment %} 
    <div>
        <a href="{% provider_login_url 'twitter' %}">Login With Twitter</a>
    </div> {% endcomment %}

 
</div>
{% endblock %}

voting/templates/voting/register.html
{% comment %} PAGE DISABLED - ONLY SOCIAL AUTH {% endcomment %}

{% extends 'voting/header.html' %}

{% block content %}
{% include "voting/includes/status.html" %}
<br>

register here

<div style="center">
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <button style="background-color:#F4EB16; color:blue" type="submit">Sign Up</button>
    </form>

</div>
{% endblock %}

voting/templates/voting/votingHomepage.html
{% extends 'voting/header.html' %}

{% block content %}
{% include "voting/includes/status.html" %}

voting homepage here
<br>
login to vote:
<br>
<br>
<a href="login">To login</a>

<br>
<a href="logout">Logout</a>
<br>
<br>
<a href="dashboard">to dashboard</a>
{% endblock %}